### ISSUE TITLE
Add option to provide Play configuration from build.sbt

### ISSUE THREAD

**Issue by bursauxa** [dwickern/sbt-swagger-play#4]
Hello,

First of all, thanks for this project, it will allow us to move forward with Scala 2.13 when our projects were stuck :+1: 

We are encountering an issue where the `application.conf` file is not available at build time, because we inject platform-specific variants at deployment time. In this case, the plugin will crash from `Configuration.load(env)` at line 18 of `SwaggerRunner.scala`.

I think one way to solve the issue would be to avoid reliance on the `application.conf` file by providing an option to define a configuration in the `build.sbt` file. The Swagger parts of the configuration are the only ones that are actually required, so this should not be excessively large.

**Comment by dwickern** [comment]
Thanks for working on this, I think it's a great idea. Configuring swagger through sbt seems more natural than using `application.conf`.

**Comment by dwickern** [comment]
Closed #5
